// Renders the per-platform landing pages into site/public.
//
// Content lives in site/pages/platforms.mjs and the shell in
// site/pages/template.html; this stitches them together and writes
// site/public/<slug>.html with a banner marking it generated. Edit the
// sources and re-run this, never the output:
//
//   node scripts/build-pages.mjs

import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pages, platforms } from '../site/pages/platforms.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const template = await readFile(
  join(root, 'site', 'pages', 'template.html'),
  'utf8',
);
const indexHtml = await readFile(
  join(root, 'site', 'public', 'index.html'),
  'utf8',
);

// The homepage is the single copy of the theme, the hero card, the rail and
// the install CTA. Regions fenced there with shared:* markers (CSS comments
// inside <style>, HTML comments in markup) are lifted verbatim wherever the
// template says {{shared:name}}.
function sharedRegion(name) {
  const fence = new RegExp(
    `(?:/\\* shared:${name} \\*/|<!-- shared:${name} -->)\\n` +
      `([\\s\\S]*?)` +
      `\\s*(?:/\\* /shared:${name} \\*/|<!-- /shared:${name} -->)`,
  );
  const match = indexHtml.match(fence);
  if (!match) {
    throw new Error(
      `shared region "${name}" not found in site/public/index.html`,
    );
  }
  return match[1].trimEnd();
}

// The FAQPage answers must be plain text, so the entities and markup in the
// HTML answers are flattened before they go into the JSON.
function plainText(html) {
  return html
    .replace(/<[^>]+>/g, '')
    .replace(/&ldquo;|&rdquo;/g, '"')
    .replace(/&rsquo;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')
    .trim();
}

// The annotated screenshots, when a page has any. Notes are percentage
// boxes over the image: [left, top, width, height], with the label chip
// placed per `labelPos` (inside | top | bottom | bottom-right) and a kind
// of removed, changed or kept.
function renderShots(shots) {
  if (!shots?.length) return '';
  const figures = shots
    .map((shot) => {
      const notes = shot.notes
        .map(
          (note) =>
            `<div class="note ${note.kind}" style="left:${note.box[0]}%;top:${note.box[1]}%;width:${note.box[2]}%;height:${note.box[3]}%">` +
            `<span class="note-label ${note.labelPos}">${note.label}</span></div>`,
        )
        .join('\n            ');
      return (
        `        <figure class="shot">\n` +
        `          <div class="shot-frame">\n` +
        `            <img src="${shot.src}" alt="${shot.alt}" width="${shot.width}" height="${shot.height}" loading="lazy" />\n` +
        `            ${notes}\n` +
        `          </div>\n` +
        `          <figcaption class="muted">${shot.caption}</figcaption>\n` +
        `        </figure>`
      );
    })
    .join('\n\n');
  return `\n        <hr class="rule" />\n\n${figures}\n`;
}

for (const page of pages) {
  const faqSections = page.faqs
    .map(
      (faq) =>
        `<h2>${faq.q}</h2>\n` +
        faq.a.map((paragraph) => `<p>${paragraph}</p>`).join('\n'),
    )
    .join('\n');

  const faqJsonLd = JSON.stringify(
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: page.faqs.map((faq) => ({
        '@type': 'Question',
        name: plainText(faq.q),
        acceptedAnswer: {
          '@type': 'Answer',
          text: faq.a.map(plainText).join(' '),
        },
      })),
    },
    null,
    2,
  );

  // Every other platform, linked when its page exists. Oxford-comma-free
  // "a, b and c" joining to match the site's prose.
  const others = platforms
    .filter((platform) => platform.slug !== page.slug)
    .map((platform) =>
      pages.some((candidate) => candidate.slug === platform.slug)
        ? `<a href="/${platform.slug}">${platform.name}</a>`
        : platform.name,
    );
  const otherPlatforms =
    others.slice(0, -1).join(', ') + ' and ' + others[others.length - 1];

  const html = template
    .replace(/\{\{shared:([a-z-]+)\}\}/g, (_, name) => sharedRegion(name))
    .replace(
      '<!doctype html>',
      '<!doctype html>\n<!-- GENERATED by scripts/build-pages.mjs from site/pages/. Edit those, not this. -->',
    )
    .replaceAll('{{TITLE}}', page.title)
    .replaceAll('{{DESCRIPTION}}', page.description)
    .replaceAll('{{SLUG}}', page.slug)
    .replaceAll('{{H1}}', page.h1)
    .replaceAll('{{LEAD}}', page.lead)
    .replaceAll('{{NAME}}', page.name)
    .replaceAll(
      '{{CHANGES_ITEMS}}',
      page.changes.map((item) => `<li>${item}</li>`).join('\n        '),
    )
    .replaceAll('{{SHOT_SECTION}}', renderShots(page.shots))
    .replaceAll('{{FAQ_SECTIONS}}', faqSections)
    .replaceAll('{{FAQ_JSONLD}}', faqJsonLd)
    .replaceAll('{{OTHER_PLATFORMS}}', otherPlatforms);

  const outPath = join(root, 'site', 'public', `${page.slug}.html`);
  await writeFile(outPath, html);
  console.log(`wrote ${outPath}`);
}
